# 项目全局设置
server:
  port: 9090

spring:
  profiles:
    active: prod-Oracle

# mybatis集成Oracle
mybatis:
  config-location: classpath:mybatis/config/mybatis-config-Oracle.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

